# Generated by Django 4.2.11 on 2025-01-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=10)),
                ('nic', models.CharField(max_length=20)),
                ('certificate', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('upload', models.FileField(upload_to='certificates/')),
                ('position', models.CharField(max_length=255)),
            ],
        ),
    ]
