# Generated by Django 5.1.4 on 2025-01-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_registration_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='date_of_birth',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
